name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for logging an issue for the docslikecode.com website. If you would like to fix it yourself, that''s fine. Assign yourself and send in a PR. You can also log issues with the book, _Docs Like Code_, and the author will see them here.'
        pr-message: 'Thanks for sending a pull request. You can message me on LinkedIn or Twitter if I don''t respond here quickly.'
